# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codaye - Let's Build Your Website
email: contact@codaye.com
description: > # this means to ignore newlines until "baseurl:"
  Codaye Technologies is a software development company committed to building beautiful,
  functional websites for individuals and businesses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codaye.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


exclude: [
  .git,
  .gitignore,
  .sass-cache,
  package.json,
  package-lock.json
  gulpfile.js,
  node_modules,
  '**/*.log',
  README.md,
]

# Site environment overrode in _config.dev.yml
env: production
